// stock settings for bearmetal server
// autogenerate ??

#include <netdb.h>

#ifndef BEARMETAL_DEFAULT_SETTINGS
#define BEARMETAL_DEFAULT_SETTINGS

# define BEARMETAL_DEFAULT_PORT      "8081"
# define BEARMETAL_DEFAULT_MAXEVENTS 256
# define BEARMETAL_DEFAULT_READBUF   8192

# define BEARMETAL_DEFAULT_BACKLOG SOMAXCONN

# define BEARMETAL_DEFAULT_AI_FAMILY   AF_UNSPEC
# define BEARMETAL_DEFAULT_AI_SOCKTYPE SOCK_STREAM
# define BEARMETAL_DEFAULT_AI_FLAGS    AI_PASSIVE

#endif
